version: '3'
services:
  sql-server:
    #hostname: msslq-db
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:latest
    #image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'localDocker0.MsSqlDev'
    ports:
      - 11433:1433